#Plugin This Create 20 June 2021
#Real Author HaykalPRO
#Don't Change This Author
name: ComunityUI
author: HaykalPRO
main: comunityui\Main
api: 3.0.0
version: 1

commands:
  comunity:
    description: §aComunity Server!
